version: 2.3.{build}
image: Visual Studio 2022


environment:
  matrix:
    - PlatformToolset: v143

platform:
    - x64
    - Win32
    - arm64

configuration:
    - Debug
    - Release


install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%platform%"=="arm64" set archi=amd64_arm64
    - if "%platform%"=="arm64" set platform_input=arm64

    - if "%PlatformToolset%"=="v143" call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NppPluginTemplate.vcxproj /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin64\SecurePad.dll" -FileName SecurePad.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\SecurePad.dll" -FileName SecurePad.dll
        }

        if ($env:PLATFORM_INPUT -eq "arm64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "arm64\SecurePad.dll" -FileName SecurePad.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v143") {
            if($env:PLATFORM_INPUT -eq "x64"){
                $ZipFileName = "SecurePad_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORM_INPUT).zip"
                7z a $ZipFileName .\bin64\SecurePad.dll
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
                $ZipFileName = "SecurePad_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORM_INPUT).zip"
                7z a $ZipFileName .\bin\SecurePad.dll
            }
            if($env:PLATFORM_INPUT -eq "arm64"){
                $ZipFileName = "SecurePad_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORM_INPUT).zip"
                7z a $ZipFileName .\arm64\SecurePad.dll
            }
        }

artifacts:
  - path: SecurePad_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v143
        configuration: Release
